CREATE DATABASE nix_jdbc WITH owner postgres;

CREATE TABLE IF NOT EXISTS role
(
	id SERIAL PRIMARY KEY,
	name VARCHAR(256) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS person
(
	id SERIAL PRIMARY KEY,
	role_id INT,
	first_name VARCHAR(256) NOT NULL,
	last_name VARCHAR(256) NOT NULL,
	login VARCHAR(256) NOT NULL UNIQUE,
	dob TIMESTAMP NOT NULL,
	password VARCHAR(256) NOT NULL,
	email VARCHAR(256) NOT NULL,
	FOREIGN KEY (role_id) REFERENCES role (id)
);
